CROSS_COMPILE = arm-none-linux-gnueabi-
STRIP = $(CROSS_COMPILE)strip
CC = $(CROSS_COMPILE)gcc

CFLAGS += -fPIC -Wall
LDFLAGS += -shared
OBJS+=$(filter %.o,$(SRC:.c=.o))

all: $(TARGET)

%.o: %.c
	@rm -f $@
	$(CC) $(CFLAGS) -c $< -o $@

version:
	bash gen_version.sh > version.h

$(TARGET): version $(OBJS)
	$(CC) $(LDFLAGS) $(OBJS) -o $@

clean:
	@for i in $(OBJS); do (if test -e "$$i"; then ( rm $$i ); fi ); done
	@rm -f $(TARGET)

