CROSS_COMPILE = gcc
STRIP = strip
#CROSS_COMPILE = arm-none-linux-gnueabi-gcc

CFLAGS += -fPIC -Wall
LDFLAGS += -shared
OBJS+=$(filter %.o,$(SRC:.c=.o))

all: $(TARGET)

%.o: %.c
	@rm -f $@
	$(CROSS_COMPILE) $(CFLAGS) $(INCLUDES) -c $< -o $@

version:
	bash gen_version.sh > version.h

$(TARGET): version $(OBJS)
	$(CROSS_COMPILE) $(LDFLAGS) $(OBJS) -o $@

clean:
	@for i in $(OBJS); do (if test -e "$$i"; then ( rm $$i ); fi ); done
	@rm -f $(TARGET)

